apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: netclab-xp
  annotations:
    meta.crossplane.io/source: https://github.com/netclab/netclab-xp
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: Declarative router configuration and lifecycle management.
    meta.crossplane.io/readme: |
      GitOps-driven lifecycle management for physical, virtual, and containerized routers.
      netclab-xp abstracts device-specific complexities, enabling consistent and reproducible network configuration.
spec:
  dependsOn:
    - apiVersion: pkg.crossplane.io/v1
      kind: Provider
      package: xpkg.upbound.io/crossplane-contrib/provider-http
      version: ">=v1.0.14"

    - apiVersion: pkg.crossplane.io/v1
      kind: Function
      package: xpkg.upbound.io/crossplane-contrib/function-go-templating
      version: ">=v0.11.1"

    - apiVersion: pkg.crossplane.io/v1
      kind: Function
      package: xpkg.upbound.io/crossplane-contrib/function-auto-ready
      version: ">=v0.5.2"

    - apiVersion: pkg.crossplane.io/v1
      kind: Function
      package: xpkg.upbound.io/crossplane-contrib/function-environment-configs
      version: ">=v0.4.0"

    - apiVersion: pkg.crossplane.io/v1
      kind: Function
      package: xpkg.upbound.io/netclab/function-eapi
      version: ">=v0.0.15"

  crossplane:
    version: ">=v2.1.1"
