apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: stpmodes.eos.netclab.dev
spec:
  defaultCompositionRef:
    name: stpmodes.eos.netclab.dev
  scope: Namespaced
  group: eos.netclab.dev
  names:
    kind: StpMode
    plural: stpmodes
    categories:
    - crossplane
    - netclab
  versions:
  - name: v1alpha1
    additionalPrinterColumns:
    - name: ENDPOINT
      type: string
      jsonPath: .spec.endpoint
    - name: STP
      type: string
      jsonPath: .spec.stpMode
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              endpoint:
                type: string
              stpMode:
                type: string
                enum:
                - none
            required:
            - endpoint
            - stpMode
